name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.host.url=http://<SONARQUBE_PUBLIC_IP>:9000 \
            -Dsonar.login=$SONAR_TOKEN

      - name: Publish to Nexus
        run: mvn deploy

      - name: Deploy to Tomcat
        run: |
          curl -T target/your-app.war "http://admin:admin@<TOMCAT_PUBLIC_IP>:8080/manager/text/deploy?path=/your-app&update=true"
